Standard nano blindsigning
trilitech/ledger-app-tezos-wallet pull request #257
Opened 2024-07-22 08:38 UTC by spalmer25

This PR:
 - Removes the blindsigning's toggle from settings. The blindsigning is always activate.
 - Changes the blindsigning texts to standard ones (see #256).

2024-07-23 14:17 UTC, ajinkyaraj-23 requested changes

2024-07-23 14:17 UTC, ajinkyaraj-23 commented on app/src/ui_stream.c
> +    if ((s->current < s->total) && (s->pressed_right)) {
succ() function is being called from change_screen_right and tz_ui_stream . At both places the s->pressed-right is either set to true or checked if its true. so when we come to succ() it is guaranteed to be true. we can add TZ_CHECK here instead of checking the if condition. if its not true there is something wrong.

2024-07-23 14:17 UTC, ajinkyaraj-23 commented on tests/integration/nano/snapshots/nanosp/test_blindsign_reject/reject_from_blind/clear/00001.png
Can we make this warning text vertically centered. Adding a newline char at the beginning could do the trick.

2024-07-23 14:17 UTC, ajinkyaraj-23 commented on tests/integration/nano/snapshots/nanosp/test_blindsign_reject/reject_from_blind/clear/00001.png
same for the next warning text also.

2024-07-23 14:22 UTC, spalmer25 commented on app/src/ui_stream.c
> +    if ((s->current < s->total) && (s->pressed_right)) {
From `change_screen_right`, `s->pressed_right` could have changed from `s->cb(TZ_UI_STREAM_CB_REFILL);`, and the case occurs since the stream is reset at parsing-error.

2024-07-23 14:25 UTC, spalmer25 commented on tests/integration/nano/snapshots/nanosp/test_blindsign_reject/reject_from_blind/clear/00001.png
Yes, I'll try to centre the arrow as well.

2024-07-24 07:22 UTC, spalmer25 commented on tests/integration/nano/snapshots/nanosp/test_blindsign_reject/reject_from_blind/clear/00001.png
Centring the arrow requires more work than expected. I'll deal with it in another PR.

2024-07-24 09:27 UTC, ajinkyaraj-23 commented on tests/integration/nano/snapshots/nanosp/test_blindsign_reject/reject_from_blind/clear/00001.png
FIne.

2024-07-24 09:32 UTC, ajinkyaraj-23 commented on tests/integration/nano/snapshots/nanosp/test_blindsign_reject/reject_from_blind/clear/00001.png
Use a HOME layout type for arrows to be in the center. See ui_stream.c:327

2024-07-24 09:48 UTC, spalmer25 commented on tests/integration/nano/snapshots/nanosp/test_blindsign_reject/reject_from_blind/clear/00001.png
HOME layout put in the center the first text line. It fit until now the screen because a maximum of 2 lines was displayed. But the warning text contains 3 lines, so the text is not centered anymore.

2024-07-24 09:52 UTC, spalmer25 commented on tests/integration/nano/snapshots/nanosp/test_blindsign_reject/reject_from_blind/clear/00001.png
Related issue: https://github.com/trilitech/ledger-app-tezos-wallet/issues/259

2024-07-24 10:09 UTC, ajinkyaraj-23 approved these changes
LGTM

2024-07-24 12:12 UTC, merged