nanos: reduce history screens to 4
trilitech/ledger-app-tezos-wallet pull request #48
Opened 2023-10-09 13:57 UTC by emturner

fixes #44

2023-10-09 14:39 UTC, emturner commented on app/src/apdu_sign.c
> -    tz_ui_stream_init(stream_cb);
It's not placed anywhere. The current STAX blindsigning workflow does not use `tz_ui_stream` at all

2023-10-09 14:41 UTC, emturner commented on app/src/apdu_sign.c
> -    tz_ui_stream_init(stream_cb);
Raised #49 to address this, as will also lead to code simplification

2023-10-09 15:29 UTC, spalmer25 commented
Reducing the number of history screens to 4 has an unexpected effect:
The "Cannot press left" icon appears in the menu when the `Blind Sign` option is activated.

2023-10-09 15:30 UTC, spalmer25 reviewed
Reducing the number of history screens to 4 has an unexpected effect:
The "Cannot press left" icon appears in the menu when the `Blind Sign` option is activated

2023-10-09 15:31 UTC, spalmer25 requested changes
Reducing the number of history screens to 4 has an unexpected effect:
The "Cannot press left" icon appears in the menu when the `Blind Sign` option is activated.
Do we change that now or leave it for later?
Something like this should fix it:
```c
// In ui_stream.c line 358
-    if (s->current > 0)
-        init[1].text = (const char *)&C_icon_go_left;
-
-    /* Unless we can't... */
-    if (s->current == s->total - TZ_UI_STREAM_HISTORY_SCREENS + 1)
-        init[1].text = (const char *)&C_icon_go_forbid;

+    if (s->current > 0) {
+        /* Unless we can't... */
+        if (s->current == s->total - TZ_UI_STREAM_HISTORY_SCREENS + 1)
+            init[1].text = (const char *)&C_icon_go_forbid;
+        else
+            init[1].text = (const char *)&C_icon_go_left;
+    }
```

2023-10-10 07:24 UTC, spalmer25 approved these changes

2023-10-11 15:55 UTC, merged