Adding the Swap feature
trilitech/ledger-app-tezos-wallet pull request #6
Opened 2023-09-13 11:25 UTC by spalmer25

This MR enables the Ledger `swap` function:
- [x] Add ENABLE_SWAP tag
- [x] Provide the 4 required functions:
  * [x] The `swap_handle_check_address` function which checks an address.
  * [x] The `swap_handle_get_printable_amount` function, which gives the print format for an amount.
  * [x] The `swap_copy_transaction_parameters` function, which backs up transaction parameters.
  * [x] The `swap_finalize_exchange_sign_transaction` function which finalizes the exchange.
- [x] During a `swap`, check that the transaction matches the backed-up parameters.

I made some choices in the implementation:
 - In `check_address`: the `derivation_type` is set to `ED25519` (since no parameter defines it).
 - In `check_address`/`copy_transaction_parameters`: the `extra_id` must be non-null and empty.
 - In the `get_printable_amount` function: the `ticker` and the number of decimals given by the caller are those used for print. Should we instead force the display with `tz` and 6 decimals?
 - In `copy_transaction_parameters`/`check_validity`: the `ticker` and the number of decimals are not taken into account, the `amount`/`fee` values are just compared without decimals.

2023-09-14 12:35 UTC, spalmer25 commented
Peer on GitLab:
https://gitlab.com/nomadic-labs/tezos-ledger-app-revamp/-/merge_requests/139

2023-09-18 09:07 UTC, emturner reviewed
overall LGTM, will test manually against ledger live

2023-09-26 07:22 UTC, spalmer25 commented on app/src/handle_swap.c
> +  derivation_type_t derivation_type = DERIVATION_TYPE_ED25519;
Perfect, I'll stick to that for this PR.

2023-09-26 19:46 UTC, elric1 requested changes

2023-09-26 19:46 UTC, elric1 commented on app/src/keys.c
> +    default: CX_CHECK(EXC_WRONG_PARAM); break;
CX_CHECK should be TZ_FAIL here.

2023-09-26 19:46 UTC, elric1 commented on app/src/keys.h
> +void generate_pkh(derivation_type_t, const bip32_path_t *, char *, size_t);
It would look better to put this prototype with the other prototypes after `generate_public_key()`.

2023-09-26 19:46 UTC, elric1 commented on app/src/keys.c
> +void
The function above (`public_key_hash()`) should be static as we've removed its prototype and it therefore should not be accessible outside this C file.

2023-09-26 20:10 UTC, elric1 commented on app/src/parser/num_parser.c
> +bool tz_print_uint64(uint64_t value, char *out, int out_len, int nb_decimals) {
We should not use "print" in these function names, because they do not print.
tz_print_mutez() can be replaced by format_fpu64() from lib_standard_app in ledger-secure-sdk, I think.
If you are worried about building it outside for, say, tests, then use the approach in app/src/parser/compat.h and define:

```
bool
tz_format_mutez(uint64_t value, char *out, size_t outlen)
{
#ifdef ACTUALLY_ON_LEDGER
    return format_fpu64(out, outlen, value, 6);
#else
    size_t len = snprintf(out, outlen, "%u.%06u", value / 1000000, value % 1000000);
    return len < outlen;
#endif
}

2023-09-26 20:11 UTC, elric1 commented on app/src/parser/num_parser.c
> +bool tz_print_uint64(uint64_t value, char *out, int out_len, int nb_decimals) {
I'm going to add the above comment to my review, if I can.

2023-09-26 20:29 UTC, elric1 requested changes
I noticed another quick one. This should simplify things quite a lot.

2023-09-26 20:29 UTC, elric1 commented on app/src/parser/num_parser.c
> +}
This duplicates functionality that is already defined in `ledger-secure-sdk/lib_standard_app/format.c`. This function should be able to be rewritten something like this:
```
bool
tz_print_mutez2(uint64_t value, char *out, int out_len, int nb_decimals)
{
#if ACTUALLY_ON_LEDGER
    format_fpu64(out, out_len, value, nb_decimals);
#else
    size_t divisor = 1;
    size_t i;
    size_t ret;

    for (i=0; i < nb_decimals; i++)
        divisor *= 10;

    ret = snprintf(out, out_len, "%u.%0*u",
                   value / divisor,  nb_decimals, value % divisor);
    return ret < out_len;
#endif
}

```

2023-09-26 20:37 UTC, elric1 commented on app/src/parser/num_parser.c
> +}
`ACTUALLY_ON_LEDGER` can be found in `app/src/parser/compat.h` which is how you decide if you are inside the unit tests.
My function assumes that if you are not on a ledger, then you are on an LP64 box with a functioning `snprintf(3)` in libc.

2023-09-27 07:42 UTC, spalmer25 commented on app/src/parser/num_parser.c
> +bool tz_print_uint64(uint64_t value, char *out, int out_len, int nb_decimals) {
Perfect!

2023-09-27 07:56 UTC, spalmer25 commented on app/src/parser/num_parser.c
> +}
This function is only useful in swap, so it would be better not to have this function in parser at all and to use the functions from `ledger-secure-sdk/lib_standard_app/format.c` directly.

2023-09-27 08:50 UTC, elric1 approved these changes

2023-09-27 09:28 UTC, merged