Makefile: build/test app on mac
trilitech/ledger-app-tezos-wallet pull request #73
Opened 2023-10-19 16:27 UTC by ajinkyaraj-23

sed command removed as it does not support \U .

2023-10-20 10:29 UTC, emturner commented on Makefile
> +	SDK=$(shell echo $* | tr "[:lower:]" "[:upper:]")_SDK;   \
nit: backlashes no longer aligned

2023-10-20 10:29 UTC, emturner commented on Makefile
> +	$(DOCKER_RUN_APP_BUILDER) bash -c                            \
nit: backslashes no longer aligned

2023-10-20 10:29 UTC, emturner commented on Makefile
> +	SDK=$(shell echo $* | tr "[:lower:]" "[:upper:]")_SDK;   \
(multiple places in the Makefile). Otherwise LGTM

2023-10-20 15:17 UTC, spalmer25 commented on Makefile
> +		test/samples/operations/nanos/samples.hex	\
```suggestion
unit_tests:	test/samples/micheline/nano/samples.hex	\
		test/samples/operations/nano/samples.hex	\
```

2023-10-26 11:20 UTC, ajinkyaraj-23 commented
After making required changes, 
I am getting one test failure in integration tests.
Please find the test result attached. 
[integration_tests.json](https://github.com/trilitech/ledger-app-tezos-wallet/files/13176661/integration_tests.json)

2023-10-26 12:28 UTC, spalmer25 commented
> After making required changes, I am getting one test failure in integration tests. Please find the test result attached. [integration_tests.json](https://github.com/trilitech/ledger-app-tezos-wallet/files/13176661/integration_tests.json)

From the json, it seems that the `$COMMIT_BYTES` variable has not been initialised correctly.
And indeed, a variable has been moved in PR https://github.com/trilitech/ledger-app-tezos-wallet/pull/93 in which a `sed` has been moved in `app_vars.sh`.

2023-10-26 14:12 UTC, emturner commented on Makefile
> +	$(DOCKER_RUN_APP_BUILDER) bash -c						\
```suggestion
	$(DOCKER_RUN_APP_BUILDER) bash -c			\
```

2023-10-26 14:12 UTC, emturner commented on Makefile
> +	$(DOCKER_RUN_APP_BUILDER) bash -c						\
```suggestion
	$(DOCKER_RUN_APP_BUILDER) bash -c			\
```

2023-10-26 14:13 UTC, emturner commented
v v minor whitespace - can be fixed in future :)

2023-10-26 15:38 UTC, emturner requested changes
The gitconfig change breaks the tests on linux

2023-10-31 09:23 UTC, emturner approved these changes

2023-10-31 09:23 UTC, merged